version: '3.4'

networks:
  frontend:
  backend:


services:
  eventcatalog:
    image: events/eventsapi
    build:
      context: .\EventsAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventsDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalEventUrl: http://localhost:3000
    ports:
      - "3000:80"
    container_name: eventcatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1248:1433"
    container_name: eventcatalogsqlserver
    networks:
      - backend